package:
  name: "valjean"
  author: "valjean developers"
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ../

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}_py{{ PY_VER }}
  script: python3 -m pip install .
  entry_points:
    - valjean = valjean.cambronne.main:main


requirements:
  build:
    - python {{PY_VER}}
    - poetry-core >=1.0.0

  run:
    - python
    - numpy
    - pyparsing >=3,<4
    - scipy
    - matplotlib
    - toml
    - h5py


test:
  imports:
    - valjean
