name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: pypi-publish
      # You may pin to the exact commit or the version.
      # uses: pypa/gh-action-pypi-publish@37f50c210e3d2f9450da2cd423303d6a14a6e29f
      uses: pypa/gh-action-pypi-publish@v1.5.1
      with:
        # Password for your PyPI user or an access token
        password: ${{ secrets.PYPI_UPLOAD_TOKEN }}
        # Show verbose output.
        verbose: true
        # Show hash values of files to be uploaded
        print_hash: true
